server:
  port: ${SERVER_PORT:8092}  # Use the environment variable

logging:
  level:
    com:
      openclassrooms:
        tourguide: DEBUG
    org:
      springframework: INFO
    root: INFO

management:
  server:
    port: ${SERVER_PORT:8092}  # Same port as the application
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always